export interface Review {
  id: number;
  author: string;
  rating: number;
  date: Date;
  comment: string;
}

export interface ProductVariant {
  size: string;
  price: number;
  oldPrice?: number;
  stock: number;
}

export interface Product {
  id: number;
  title: string;
  category:
    | "Watches"
    | "Bags"
    | "Shoes"
    | "Accessories"
    | "Chair"
    | "Table"
    | "Sofa"
    | "Decor"
    | "Home"
    | "Furniture"
    | "Kitchen"
    | "Bath"
    | "Garden"
    | "Office"
    | "Fitness"
    | "Electronics";
  price: number;
  oldPrice?: number;
  discountPercent?: number;
  rating: number;
  images: string[];
  countdownEnd: Date | null;
  status: "In Stock" | "Low Stock" | "Out of Stock";
  variants: ProductVariant[];
  reviews: Review[];
  details: string;
  style: "Casual" | "Formal" | "Sport" | "Luxury";
  size: "Small" | "Medium" | "Large" | "Extra Large";
  color:
    | "Black"
    | "Silver"
    | "Gold"
    | "Blue"
    | "Red"
    | "Brown"
    | "White"
    | "Multiple";
}

export const generateSlug = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");

export const applyDiscount = (oldPrice: number, discountPercent: number) =>
  +(oldPrice - oldPrice * (discountPercent / 100)).toFixed(2);

const now = Date.now();

export const products: Product[] = [
  {
    id: 1,
    title: "Wooden Sofa Chair",
    category: "Chair",
    price: applyDiscount(299.99, 50),
    oldPrice: 299.99,
    discountPercent: 50,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/d5/9b/13/d59b13fc73185eaa13c2efb5bfe8323e.jpg",
      "https://i.pinimg.com/736x/72/b1/13/72b1137310fb10a9da7a337ec6d16cf8.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Brown",
    variants: [
      {
        size: "Small",
        price: applyDiscount(249.99, 50),
        oldPrice: 249.99,
        stock: 15,
      },
      {
        size: "Medium",
        price: applyDiscount(299.99, 50),
        oldPrice: 299.99,
        stock: 10,
      },
      {
        size: "Large",
        price: applyDiscount(349.99, 50),
        oldPrice: 349.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "John Doe",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "Extremely comfortable and stylish!",
      },
      {
        id: 2,
        author: "Jane Smith",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Good quality wood and craftsmanship.",
      },
    ],
    details: `This exquisite wooden sofa chair combines timeless elegance with modern comfort. Crafted from premium solid oak wood with a natural finish that highlights the wood's beautiful grain patterns...`,
  },
  {
    id: 2,
    title: "Office Chair",
    category: "Chair",
    price: applyDiscount(129.99, 20),
    oldPrice: 129.99,
    discountPercent: 20,
    rating: 4.0,
    images: [
      "https://i.pinimg.com/736x/c6/14/cd/c614cdc02eda462847fb9e7b968ec997.jpg",
      "https://i.pinimg.com/736x/4e/65/5f/4e655f54c207a4b02e5292c9dd764b53.jpg",
      "https://i.pinimg.com/736x/e7/b5/83/e7b5839e9c76fda4ac87012e1b896542.jpg",
    ],
    countdownEnd: new Date(now + 26 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(129.99, 20),
        oldPrice: 129.99,
        stock: 20,
      },
      {
        size: "Executive",
        price: applyDiscount(159.99, 20),
        oldPrice: 159.99,
        stock: 12,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Mike Johnson",
        rating: 4,
        date: new Date(2023, 6, 10),
        comment: "Good value for the price.",
      },
      {
        id: 2,
        author: "Sarah Wilson",
        rating: 3,
        date: new Date(2023, 5, 5),
        comment: "Comfortable but assembly was tricky.",
      },
    ],
    details: `Designed for productivity and comfort, this office chair features an advanced ergonomic design that supports your body through long work hours...`,
  },
  {
    id: 3,
    title: "Luxury Armchair",
    category: "Chair",
    price: applyDiscount(349.99, 30),
    oldPrice: 349.99,
    discountPercent: 30,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/1200x/74/b9/5c/74b95c4146ab36f8e407d021447d7a5e.jpg",
      "https://i.pinimg.com/736x/89/ab/cd/89abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "Low Stock",
    style: "Luxury",
    size: "Large",
    color: "Gold",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(349.99, 30),
        oldPrice: 349.99,
        stock: 3,
      },
      {
        size: "Oversized",
        price: applyDiscount(399.99, 30),
        oldPrice: 399.99,
        stock: 2,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Emily Davis",
        rating: 5,
        date: new Date(2023, 7, 18),
        comment: "Absolutely luxurious and so comfortable!",
      },
      {
        id: 2,
        author: "Robert Brown",
        rating: 4,
        date: new Date(2023, 6, 30),
        comment: "Beautiful addition to our living room.",
      },
    ],
    details: `Experience unparalleled luxury with this exquisite armchair that combines sophisticated design with exceptional comfort...`,
  },
  {
    id: 4,
    title: "Recliner Chair",
    category: "Chair",
    price: applyDiscount(399.99, 25),
    oldPrice: 399.99,
    discountPercent: 25,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/28/01/fb/2801fb2d5a8f8942d483bf8097eb7896.jpg",
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Large",
    color: "Brown",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(399.99, 25),
        oldPrice: 399.99,
        stock: 7,
      },
      {
        size: "Wide",
        price: applyDiscount(449.99, 25),
        oldPrice: 449.99,
        stock: 5,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "David Miller",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "Best recliner I have ever owned!",
      },
      {
        id: 2,
        author: "Lisa Taylor",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "Very comfortable and easy to operate.",
      },
    ],
    details: `Designed for ultimate relaxation, this premium recliner chair features a smooth mechanism that allows you to effortlessly transition from upright to fully reclined positions...`,
  },
  {
    id: 5,
    title: "Gaming Chair",
    category: "Chair",
    price: applyDiscount(499.99, 30),
    oldPrice: 499.99,
    discountPercent: 30,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/d4/12/e0/d412e05ed8464bd0390f13697c3e17be.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 40 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Large",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(499.99, 30),
        oldPrice: 499.99,
        stock: 15,
      },
      {
        size: "XL",
        price: applyDiscount(549.99, 30),
        oldPrice: 549.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Alex Chen",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "Perfect for long gaming sessions!",
      },
      {
        id: 2,
        author: "Mark Wilson",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "Great lumbar support and build quality.",
      },
    ],
    details: `Engineered for serious gamers and professionals who spend extended periods seated, this gaming chair combines ergonomic design with premium features...`,
  },
  {
    id: 6,
    title: "Modern Dining Table",
    category: "Table",
    price: applyDiscount(599.99, 15),
    oldPrice: 599.99,
    discountPercent: 15,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/8d/9b/1e/8d9b1ee2c3e1e9a3b9d0e2e5c8e3e4f5.jpg",
      "https://i.pinimg.com/736x/2b/3b/1a/2b3b1a2a3a1b3c9b7e7a5e8e3e4f5.jpg",
    ],
    countdownEnd: new Date(now + 28 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Large",
    color: "Brown",
    variants: [
      {
        size: "6-seater",
        price: applyDiscount(599.99, 15),
        oldPrice: 599.99,
        stock: 9,
      },
      {
        size: "8-seater",
        price: applyDiscount(749.99, 15),
        oldPrice: 749.99,
        stock: 5,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Jessica Lee",
        rating: 5,
        date: new Date(2023, 7, 10),
        comment: "Elegant and sturdy, perfect for family dinners!",
      },
      {
        id: 2,
        author: "Kevin White",
        rating: 4,
        date: new Date(2023, 6, 25),
        comment: "Looks great in our kitchen, assembly was simple.",
      },
    ],
    details: `Crafted from high-quality, solid wood with a sleek, minimalist design, this dining table is the perfect centerpiece for any modern dining room...`,
  },
  {
    id: 7,
    title: "Sleek Side Table",
    category: "Table",
    price: applyDiscount(79.99, 10),
    oldPrice: 79.99,
    discountPercent: 10,
    rating: 4.2,
    images: [
      "https://i.pinimg.com/736x/91/9c/e6/919ce663c9b4d5e6f7g8h9i0j1k2l3m4n5o6p7q.jpg",
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
    ],
    countdownEnd: new Date(now + 22 * 60 * 60 * 1000),
    status: "Low Stock",
    style: "Casual",
    size: "Small",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(79.99, 10),
        oldPrice: 79.99,
        stock: 4,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Rachel Green",
        rating: 4,
        date: new Date(2023, 9, 1),
        comment: "Just the right size for my lamp and books.",
      },
      {
        id: 2,
        author: "Joey Tribbiani",
        rating: 4,
        date: new Date(2023, 8, 20),
        comment: "Easy to move around, sturdy enough.",
      },
    ],
    details: `This sleek and compact side table is the perfect addition to any living room or bedroom. Its minimalist design and sturdy construction make it a versatile piece of furniture...`,
  },
  {
    id: 8,
    title: "Glass Coffee Table",
    category: "Table",
    price: applyDiscount(199.99, 20),
    oldPrice: 199.99,
    discountPercent: 20,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/a2/4c/e4/a24ce4e2d5a2a1a4c9b4e2d5a2a1a4c9.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 30 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Luxury",
    size: "Medium",
    color: "Silver",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(199.99, 20),
        oldPrice: 199.99,
        stock: 11,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Phoebe Buffay",
        rating: 5,
        date: new Date(2023, 10, 5),
        comment: "Looks stunning and is surprisingly durable.",
      },
      {
        id: 2,
        author: "Chandler Bing",
        rating: 4,
        date: new Date(2023, 9, 25),
        comment: "A little hard to keep clean, but worth it for the look.",
      },
    ],
    details: `Elevate your living space with this modern glass coffee table. The tempered glass top and polished metal base create a sophisticated and airy feel...`,
  },
  {
    id: 9,
    title: "Wooden Dining Table",
    category: "Table",
    price: applyDiscount(499.99, 25),
    oldPrice: 499.99,
    discountPercent: 25,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/b3/5d/4f/b35d4f2e5c8e3e4f5.jpg",
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 42 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Extra Large",
    color: "Brown",
    variants: [
      {
        size: "6-seater",
        price: applyDiscount(499.99, 25),
        oldPrice: 499.99,
        stock: 10,
      },
      {
        size: "10-seater",
        price: applyDiscount(649.99, 25),
        oldPrice: 649.99,
        stock: 6,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Ross Geller",
        rating: 5,
        date: new Date(2023, 11, 1),
        comment:
          "Incredibly solid and beautifully finished. A true heirloom piece.",
      },
      {
        id: 2,
        author: "Monica Geller",
        rating: 5,
        date: new Date(2023, 10, 15),
        comment: "Perfect for our holiday gatherings!",
      },
    ],
    details: `This robust and classic dining table is made from sustainably sourced solid wood, designed to be the focal point of your dining room...`,
  },
  {
    id: 10,
    title: "Outdoor Coffee Table",
    category: "Table",
    price: applyDiscount(149.99, 15),
    oldPrice: 149.99,
    discountPercent: 15,
    rating: 4.1,
    images: [
      "https://i.pinimg.com/736x/c4/5d/6f/c45d6f2e5c8e3e4f5.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 38 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Silver",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(149.99, 15),
        oldPrice: 149.99,
        stock: 14,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Richard Burke",
        rating: 4,
        date: new Date(2023, 8, 2),
        comment: "Durable and weather-resistant, perfect for our patio.",
      },
      {
        id: 2,
        author: "Carol Willick",
        rating: 4,
        date: new Date(2023, 7, 28),
        comment: "Looks great with our outdoor furniture set.",
      },
    ],
    details: `Built to withstand the elements, this weather-resistant outdoor coffee table is made from durable aluminum and features a stylish, minimalist design...`,
  },
  {
    id: 11,
    title: "Leather Sofa Set",
    category: "Sofa",
    price: applyDiscount(1999.99, 20),
    oldPrice: 1999.99,
    discountPercent: 20,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 72 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Luxury",
    size: "Extra Large",
    color: "Brown",
    variants: [
      {
        size: "3-seater",
        price: applyDiscount(1999.99, 20),
        oldPrice: 1999.99,
        stock: 5,
      },
      {
        size: "5-seater",
        price: applyDiscount(2499.99, 20),
        oldPrice: 2499.99,
        stock: 3,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Michael Scott",
        rating: 5,
        date: new Date(2023, 6, 15),
        comment: "Absolutely stunning! The leather quality is exceptional.",
      },
      {
        id: 2,
        author: "Pam Beesly",
        rating: 4,
        date: new Date(2023, 5, 22),
        comment: "Very comfortable and looks great in our living room.",
      },
    ],
    details: `This premium leather sofa set is crafted from top-grain leather with a rich, supple feel that only gets better with age...`,
  },
  {
    id: 12,
    title: "Sectional Sofa",
    category: "Sofa",
    price: applyDiscount(1599.99, 15),
    oldPrice: 1599.99,
    discountPercent: 15,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 60 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Extra Large",
    color: "Blue",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(1599.99, 15),
        oldPrice: 1599.99,
        stock: 7,
      },
      {
        size: "With Chaise",
        price: applyDiscount(1899.99, 15),
        oldPrice: 1899.99,
        stock: 4,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Jim Halpert",
        rating: 5,
        date: new Date(2023, 7, 10),
        comment: "Perfect for movie nights with the family!",
      },
      {
        id: 2,
        author: "Dwight Schrute",
        rating: 4,
        date: new Date(2023, 6, 25),
        comment: "Sturdy construction and comfortable seating.",
      },
    ],
    details: `This versatile sectional sofa offers customizable configuration options to fit any living space...`,
  },
  {
    id: 13,
    title: "Velvet Loveseat",
    category: "Sofa",
    price: applyDiscount(899.99, 25),
    oldPrice: 899.99,
    discountPercent: 25,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "Low Stock",
    style: "Luxury",
    size: "Medium",
    color: "Red",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(899.99, 25),
        oldPrice: 899.99,
        stock: 3,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Angela Martin",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "Elegant and sophisticated addition to our sitting room.",
      },
      {
        id: 2,
        author: "Oscar Martinez",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "The velvet fabric is luxurious to the touch.",
      },
    ],
    details: `This elegant velvet loveseat adds a touch of glamour to any room with its plush upholstery and refined silhouette...`,
  },
  {
    id: 14,
    title: "Convertible Sofa Bed",
    category: "Sofa",
    price: applyDiscount(749.99, 30),
    oldPrice: 749.99,
    discountPercent: 30,
    rating: 4.3,
    images: [
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Large",
    color: "Black",
    variants: [
      {
        size: "Twin",
        price: applyDiscount(749.99, 30),
        oldPrice: 749.99,
        stock: 8,
      },
      {
        size: "Full",
        price: applyDiscount(899.99, 30),
        oldPrice: 899.99,
        stock: 6,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Kelly Kapoor",
        rating: 4,
        date: new Date(2023, 9, 12),
        comment: "Perfect for my small apartment when guests stay over.",
      },
      {
        id: 2,
        author: "Ryan Howard",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "Easy to convert and surprisingly comfortable as a bed.",
      },
    ],
    details: `This space-saving convertible sofa bed offers dual functionality as both comfortable seating and a convenient sleeping solution...`,
  },
  {
    id: 15,
    title: "Mid-Century Modern Sofa",
    category: "Sofa",
    price: applyDiscount(1299.99, 20),
    oldPrice: 1299.99,
    discountPercent: 20,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/cd/ef/12/cdef1234567890abcdef1234567890ab.jpg",
    ],
    countdownEnd: new Date(now + 54 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Large",
    color: "Brown",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(1299.99, 20),
        oldPrice: 1299.99,
        stock: 6,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Stanley Hudson",
        rating: 5,
        date: new Date(2023, 10, 1),
        comment: "Timeless design that complements our home perfectly.",
      },
      {
        id: 2,
        author: "Phyllis Vance",
        rating: 5,
        date: new Date(2023, 9, 15),
        comment: "Beautiful craftsmanship and very comfortable.",
      },
    ],
    details: `Inspired by classic mid-century design, this sofa features clean lines, tapered legs, and premium upholstery for a timeless look...`,
  },
  {
    id: 16,
    title: "Decorative Wall Mirror",
    category: "Decor",
    price: applyDiscount(149.99, 25),
    oldPrice: 149.99,
    discountPercent: 25,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Luxury",
    size: "Large",
    color: "Silver",
    variants: [
      {
        size: "Medium",
        price: applyDiscount(149.99, 25),
        oldPrice: 149.99,
        stock: 12,
      },
      {
        size: "Large",
        price: applyDiscount(199.99, 25),
        oldPrice: 199.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Meredith Palmer",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "Makes my entryway look so much bigger and brighter!",
      },
      {
        id: 2,
        author: "Creed Bratton",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Nice ornate frame, good quality for the price.",
      },
    ],
    details: `This stunning decorative wall mirror features an intricately designed frame that adds elegance and visual interest to any space...`,
  },
  {
    id: 17,
    title: "Ceramic Table Lamp",
    category: "Decor",
    price: applyDiscount(79.99, 20),
    oldPrice: 79.99,
    discountPercent: 20,
    rating: 4.3,
    images: [
      "https://i.pinimg.com/736x/cd/ef/12/cdef1234567890abcdef1234567890ab.jpg",
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
    ],
    countdownEnd: new Date(now + 30 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Blue",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(79.99, 20),
        oldPrice: 79.99,
        stock: 15,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Toby Flenderson",
        rating: 4,
        date: new Date(2023, 6, 10),
        comment: "Provides perfect ambient lighting for my reading nook.",
      },
      {
        id: 2,
        author: "Holly Flax",
        rating: 5,
        date: new Date(2023, 5, 5),
        comment: "Beautiful craftsmanship and the ceramic finish is lovely.",
      },
    ],
    details: `This handcrafted ceramic table lamp combines artistic design with functional lighting to create a beautiful accent piece for any room...`,
  },
  {
    id: 18,
    title: "Wall Art Set",
    category: "Decor",
    price: applyDiscount(129.99, 30),
    oldPrice: 129.99,
    discountPercent: 30,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
    ],
    countdownEnd: new Date(now + 42 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Multiple",
    variants: [
      {
        size: "3-piece",
        price: applyDiscount(129.99, 30),
        oldPrice: 129.99,
        stock: 20,
      },
      {
        size: "5-piece",
        price: applyDiscount(199.99, 30),
        oldPrice: 199.99,
        stock: 12,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Jan Levinson",
        rating: 5,
        date: new Date(2023, 7, 18),
        comment: "These transformed my living room! The colors are vibrant.",
      },
      {
        id: 2,
        author: "David Wallace",
        rating: 4,
        date: new Date(2023, 6, 30),
        comment: "High-quality prints that look more expensive than they are.",
      },
    ],
    details: `This curated set of wall art features complementary designs that work together to create a cohesive gallery wall display...`,
  },
  {
    id: 19,
    title: "Decorative Throw Pillows",
    category: "Decor",
    price: applyDiscount(49.99, 40),
    oldPrice: 49.99,
    discountPercent: 40,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 18 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Small",
    color: "Multiple",
    variants: [
      {
        size: "Set of 2",
        price: applyDiscount(49.99, 40),
        oldPrice: 49.99,
        stock: 25,
      },
      {
        size: "Set of 4",
        price: applyDiscount(89.99, 40),
        oldPrice: 89.99,
        stock: 18,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Erin Hannon",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "So soft and the patterns are even prettier in person!",
      },
      {
        id: 2,
        author: "Gabe Lewis",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "Great way to add a pop of color to my neutral sofa.",
      },
    ],
    details: `These decorative throw pillows feature premium fabrics and on-trend patterns that instantly refresh any living space...`,
  },
  {
    id: 20,
    title: "Scented Candles Set",
    category: "Decor",
    price: applyDiscount(39.99, 35),
    oldPrice: 39.99,
    discountPercent: 35,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Luxury",
    size: "Small",
    color: "Multiple",
    variants: [
      {
        size: "3 candles",
        price: applyDiscount(39.99, 35),
        oldPrice: 39.99,
        stock: 30,
      },
      {
        size: "6 candles",
        price: applyDiscount(69.99, 35),
        oldPrice: 69.99,
        stock: 22,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Nellie Bertram",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "The fragrances are heavenly and the jars are reusable!",
      },
      {
        id: 2,
        author: "Pete Miller",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "Long-lasting burn time and beautiful presentation.",
      },
    ],
    details: `This luxurious set of scented candles features premium soy wax blends with sophisticated fragrance profiles that create an inviting atmosphere...`,
  },
  {
    id: 21,
    title: "Smart Watch Series 7",
    category: "Watches",
    price: applyDiscount(349.99, 15),
    oldPrice: 349.99,
    discountPercent: 15,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Small",
    color: "Black",
    variants: [
      {
        size: "40mm",
        price: applyDiscount(349.99, 15),
        oldPrice: 349.99,
        stock: 15,
      },
      {
        size: "44mm",
        price: applyDiscount(379.99, 15),
        oldPrice: 379.99,
        stock: 12,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Andy Bernard",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "The always-on display is a game changer!",
      },
      {
        id: 2,
        author: "Clark Green",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Battery life is impressive for all the features it offers.",
      },
    ],
    details: `The latest smartwatch with an always-on retina display, advanced health monitoring features, and water resistance up to 50 meters...`,
  },
  {
    id: 22,
    title: "Luxury Dress Watch",
    category: "Watches",
    price: applyDiscount(599.99, 20),
    oldPrice: 599.99,
    discountPercent: 20,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "Low Stock",
    style: "Luxury",
    size: "Medium",
    color: "Gold",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(599.99, 20),
        oldPrice: 599.99,
        stock: 4,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Robert California",
        rating: 5,
        date: new Date(2023, 6, 10),
        comment: "Exquisite craftsmanship and attention to detail.",
      },
      {
        id: 2,
        author: "Jo Bennett",
        rating: 5,
        date: new Date(2023, 5, 5),
        comment: "The perfect statement piece for formal occasions.",
      },
    ],
    details: `This elegant dress watch features a sapphire crystal face, genuine leather strap, and precision quartz movement for exceptional accuracy...`,
  },
  {
    id: 23,
    title: "Designer Handbag",
    category: "Bags",
    price: applyDiscount(299.99, 25),
    oldPrice: 299.99,
    discountPercent: 25,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/cd/ef/12/cdef1234567890abcdef1234567890ab.jpg",
    ],
    countdownEnd: new Date(now + 42 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Luxury",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "Small",
        price: applyDiscount(249.99, 25),
        oldPrice: 249.99,
        stock: 8,
      },
      {
        size: "Medium",
        price: applyDiscount(299.99, 25),
        oldPrice: 299.99,
        stock: 6,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Cathy Simms",
        rating: 5,
        date: new Date(2023, 7, 18),
        comment: "The leather quality is exceptional for the price point.",
      },
      {
        id: 2,
        author: "Isabel Poreba",
        rating: 4,
        date: new Date(2023, 6, 30),
        comment: "Spacious interior with well-designed compartments.",
      },
    ],
    details: `This sophisticated designer handbag features premium genuine leather, gold-tone hardware, and thoughtful interior organization...`,
  },
  {
    id: 24,
    title: "Running Shoes",
    category: "Shoes",
    price: applyDiscount(129.99, 30),
    oldPrice: 129.99,
    discountPercent: 30,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Medium",
    color: "Blue",
    variants: [
      {
        size: "US 7",
        price: applyDiscount(129.99, 30),
        oldPrice: 129.99,
        stock: 10,
      },
      {
        size: "US 8",
        price: applyDiscount(129.99, 30),
        oldPrice: 129.99,
        stock: 15,
      },
      {
        size: "US 9",
        price: applyDiscount(129.99, 30),
        oldPrice: 129.99,
        stock: 12,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Darryl Philbin",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "Best running shoes I've ever owned! So comfortable.",
      },
      {
        id: 2,
        author: "Val Johnson",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "Great cushioning and support for long runs.",
      },
    ],
    details: `These performance running shoes feature advanced cushioning technology, breathable mesh uppers, and durable rubber outsoles for optimal traction...`,
  },
  {
    id: 25,
    title: "Wireless Earbuds",
    category: "Electronics",
    price: applyDiscount(159.99, 20),
    oldPrice: 159.99,
    discountPercent: 20,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
    ],
    countdownEnd: new Date(now + 30 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Small",
    color: "White",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(159.99, 20),
        oldPrice: 159.99,
        stock: 20,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Kevin Malone",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "The noise cancellation is amazing!",
      },
      {
        id: 2,
        author: "Oscar Martinez",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "Comfortable fit and impressive battery life.",
      },
    ],
    details: `These premium wireless earbuds feature active noise cancellation, transparency mode, and spatial audio for an immersive listening experience...`,
  },
  {
    id: 26,
    title: "Stainless Steel Cookware Set",
    category: "Kitchen",
    price: applyDiscount(299.99, 25),
    oldPrice: 299.99,
    discountPercent: 25,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Large",
    color: "Silver",
    variants: [
      {
        size: "10-piece",
        price: applyDiscount(299.99, 25),
        oldPrice: 299.99,
        stock: 10,
      },
      {
        size: "15-piece",
        price: applyDiscount(399.99, 25),
        oldPrice: 399.99,
        stock: 7,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Kevin Malone",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "Even heat distribution makes cooking so much easier!",
      },
      {
        id: 2,
        author: "Kelly Kapoor",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Beautiful set that looks great hanging in my kitchen.",
      },
    ],
    details: `This professional-grade stainless steel cookware set features aluminum cores for even heat distribution and stay-cool handles for comfortable cooking...`,
  },
  {
    id: 27,
    title: "Non-Stick Frying Pan Set",
    category: "Kitchen",
    price: applyDiscount(89.99, 30),
    oldPrice: 89.99,
    discountPercent: 30,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "3-piece",
        price: applyDiscount(89.99, 30),
        oldPrice: 89.99,
        stock: 15,
      },
      {
        size: "5-piece",
        price: applyDiscount(129.99, 30),
        oldPrice: 129.99,
        stock: 12,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Meredith Palmer",
        rating: 4,
        date: new Date(2023, 6, 10),
        comment: "Cleanup is a breeze with these pans!",
      },
      {
        id: 2,
        author: "Phyllis Vance",
        rating: 5,
        date: new Date(2023, 5, 5),
        comment: "The non-stick surface works perfectly.",
      },
    ],
    details: `This set of non-stick frying pans features a durable ceramic coating that's free of PFOA and PTFE, making them a healthier choice for your family...`,
  },
  {
    id: 28,
    title: "Stand Mixer",
    category: "Kitchen",
    price: applyDiscount(249.99, 20),
    oldPrice: 249.99,
    discountPercent: 20,
    rating: 4.9,
    images: [
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Red",
    variants: [
      {
        size: "4.5QT",
        price: applyDiscount(249.99, 20),
        oldPrice: 249.99,
        stock: 8,
      },
      {
        size: "5.5QT",
        price: applyDiscount(299.99, 20),
        oldPrice: 299.99,
        stock: 6,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Pam Beesly",
        rating: 5,
        date: new Date(2023, 7, 18),
        comment: "Makes baking so much easier and more enjoyable!",
      },
      {
        id: 2,
        author: "Angela Martin",
        rating: 5,
        date: new Date(2023, 6, 30),
        comment: "Powerful motor handles even the thickest dough with ease.",
      },
    ],
    details: `This powerful stand mixer features a durable motor, multiple speed settings, and includes several attachments for mixing, kneading, and whipping...`,
  },
  {
    id: 29,
    title: "Air Fryer Oven",
    category: "Kitchen",
    price: applyDiscount(149.99, 25),
    oldPrice: 149.99,
    discountPercent: 25,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 42 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Silver",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(149.99, 25),
        oldPrice: 149.99,
        stock: 12,
      },
      {
        size: "XL",
        price: applyDiscount(179.99, 25),
        oldPrice: 179.99,
        stock: 9,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Stanley Hudson",
        rating: 4,
        date: new Date(2023, 8, 5),
        comment: "Crispy food with less oil - my doctor will be pleased!",
      },
      {
        id: 2,
        author: "Kevin Malone",
        rating: 5,
        date: new Date(2023, 7, 22),
        comment: "I use this every day - it's so versatile and easy to clean.",
      },
    ],
    details: `This multi-functional air fryer oven uses rapid air technology to fry, bake, roast, and grill with little to no oil for healthier meals...`,
  },
  {
    id: 30,
    title: "Coffee Maker",
    category: "Kitchen",
    price: applyDiscount(129.99, 30),
    oldPrice: 129.99,
    discountPercent: 30,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/cd/ef/12/cdef1234567890abcdef1234567890ab.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "Single Serve",
        price: applyDiscount(129.99, 30),
        oldPrice: 129.99,
        stock: 15,
      },
      {
        size: "12-Cup",
        price: applyDiscount(149.99, 30),
        oldPrice: 149.99,
        stock: 10,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Michael Scott",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "Brews perfect coffee every time! My employees love it.",
      },
      {
        id: 2,
        author: "Dwight Schrute",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "Programmable feature means coffee is ready when I wake up.",
      },
    ],
    details: `This programmable coffee maker features thermal carafe technology to keep coffee hot for hours, a built-in water filter, and multiple brew strength options...`,
  },
  {
    id: 31,
    title: "Yoga Mat",
    category: "Fitness",
    price: applyDiscount(49.99, 40),
    oldPrice: 49.99,
    discountPercent: 40,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Large",
    color: "Blue",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(49.99, 40),
        oldPrice: 49.99,
        stock: 20,
      },
      {
        size: "Extra Thick",
        price: applyDiscount(69.99, 40),
        oldPrice: 69.99,
        stock: 15,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Jan Levinson",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "Perfect cushioning for my joints during yoga practice.",
      },
      {
        id: 2,
        author: "Holly Flax",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Non-slip surface really works, even during hot yoga.",
      },
    ],
    details: `This premium yoga mat features a non-slip surface, extra cushioning for joint support, and is made from eco-friendly materials...`,
  },
  {
    id: 32,
    title: "Dumbbell Set",
    category: "Fitness",
    price: applyDiscount(129.99, 25),
    oldPrice: 129.99,
    discountPercent: 25,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "20lb Set",
        price: applyDiscount(129.99, 25),
        oldPrice: 129.99,
        stock: 12,
      },
      {
        size: "40lb Set",
        price: applyDiscount(199.99, 25),
        oldPrice: 199.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Roy Anderson",
        rating: 4,
        date: new Date(2023, 6, 10),
        comment: "Solid construction and comfortable grips.",
      },
      {
        id: 2,
        author: "Darryl Philbin",
        rating: 5,
        date: new Date(2023, 5, 5),
        comment: "Perfect for home workouts. Saves me a gym membership.",
      },
    ],
    details: `This adjustable dumbbell set allows you to change weight quickly with a simple dial system, saving space while providing a complete strength training solution...`,
  },
  {
    id: 33,
    title: "Resistance Bands Set",
    category: "Fitness",
    price: applyDiscount(39.99, 35),
    oldPrice: 39.99,
    discountPercent: 35,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Small",
    color: "White",
    variants: [
      {
        size: "5-band set",
        price: applyDiscount(39.99, 35),
        oldPrice: 39.99,
        stock: 25,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Kelly Kapoor",
        rating: 4,
        date: new Date(2023, 7, 18),
        comment:
          "So versatile! I use these for strength training and stretching.",
      },
      {
        id: 2,
        author: "Erin Hannon",
        rating: 5,
        date: new Date(2023, 6, 30),
        comment: "Travels easily - I never miss a workout on business trips.",
      },
    ],
    details: `This set of resistance bands includes multiple resistance levels, handles, ankle straps, and a door anchor for a complete full-body workout anywhere...`,
  },
  {
    id: 34,
    title: "Fitness Tracker",
    category: "Fitness",
    price: applyDiscount(89.99, 30),
    oldPrice: 89.99,
    discountPercent: 30,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Small",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(89.99, 30),
        oldPrice: 89.99,
        stock: 18,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Toby Flenderson",
        rating: 4,
        date: new Date(2023, 8, 5),
        comment: "Accurate step counting and sleep tracking features.",
      },
      {
        id: 2,
        author: "Pete Miller",
        rating: 5,
        date: new Date(2023, 7, 22),
        comment: "Battery lasts over a week with regular use!",
      },
    ],
    details: `This advanced fitness tracker monitors steps, distance, calories burned, sleep quality, and heart rate with a sleek, lightweight design that's comfortable to wear 24/7...`,
  },
  {
    id: 35,
    title: "Smart Fitness Mirror",
    category: "Fitness",
    price: 1499.99,
    oldPrice: undefined,
    discountPercent: 0,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/1200x/90/74/55/9074551a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: null,
    status: "In Stock",
    style: "Sport",
    size: "Large",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: 1499.99,
        oldPrice: undefined,
        stock: 6,
      },
      {
        size: "Pro (with camera)",
        price: 1799.99,
        oldPrice: undefined,
        stock: 3,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Fitness Enthusiast Jen",
        rating: 5,
        date: new Date(2023, 1, 22),
        comment:
          "Space-saving and effective. The live classes make me feel like I have a personal trainer.",
      },
      {
        id: 2,
        author: "Busy Professional Mark",
        rating: 4,
        date: new Date(2023, 3, 14),
        comment:
          "Perfect solution for fitting workouts into my schedule. The form feedback is incredibly helpful.",
      },
    ],
    details: `Interactive fitness mirror that transforms into a full-home gym experience when powered on...`,
  },
  {
    id: 36,
    title: "Bluetooth Speaker",
    category: "Electronics",
    price: applyDiscount(129.99, 25),
    oldPrice: 129.99,
    discountPercent: 25,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Blue",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(129.99, 25),
        oldPrice: 129.99,
        stock: 15,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Ryan Howard",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "Incredible sound quality for its size!",
      },
      {
        id: 2,
        author: "Kelly Kapoor",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Waterproof feature makes it perfect for pool parties.",
      },
    ],
    details: `This portable Bluetooth speaker delivers powerful, crystal-clear sound with deep bass, waterproof construction, and up to 24 hours of playtime...`,
  },
  {
    id: 37,
    title: "Tablet",
    category: "Electronics",
    price: applyDiscount(399.99, 20),
    oldPrice: 399.99,
    discountPercent: 20,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/cd/ef/12/cdef1234567890abcdef1234567890ab.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Silver",
    variants: [
      {
        size: "32GB",
        price: applyDiscount(399.99, 20),
        oldPrice: 399.99,
        stock: 10,
      },
      {
        size: "64GB",
        price: applyDiscount(449.99, 20),
        oldPrice: 449.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Jim Halpert",
        rating: 5,
        date: new Date(2023, 6, 10),
        comment: "Perfect for watching movies and browsing the web.",
      },
      {
        id: 2,
        author: "Pam Beesly",
        rating: 4,
        date: new Date(2023, 5, 5),
        comment: "Crisp display and long battery life.",
      },
    ],
    details: `This powerful tablet features a high-resolution display, fast processor, all-day battery life, and compatibility with a stylus for note-taking and drawing...`,
  },
  {
    id: 38,
    title: "Noise Cancelling Headphones",
    category: "Electronics",
    price: applyDiscount(299.99, 25),
    oldPrice: 299.99,
    discountPercent: 25,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Sport",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(299.99, 25),
        oldPrice: 299.99,
        stock: 12,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Stanley Hudson",
        rating: 5,
        date: new Date(2023, 7, 18),
        comment: "The noise cancellation is incredible on my commute.",
      },
      {
        id: 2,
        author: "Phyllis Vance",
        rating: 4,
        date: new Date(2023, 6, 30),
        comment: "Comfortable for long listening sessions.",
      },
    ],
    details: `These premium noise-cancelling headphones feature adaptive sound control, exceptional audio quality, and comfortable over-ear design for extended wear...`,
  },
  {
    id: 39,
    title: "Smart Home Hub",
    category: "Electronics",
    price: applyDiscount(149.99, 30),
    oldPrice: 149.99,
    discountPercent: 30,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Small",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(149.99, 30),
        oldPrice: 149.99,
        stock: 15,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Dwight Schrute",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "Finally, my smart devices all work together seamlessly!",
      },
      {
        id: 2,
        author: "Michael Scott",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "Voice control makes me feel like I'm in the future.",
      },
    ],
    details: `This smart home hub connects and controls all your compatible smart devices from one central platform, with voice control and automation capabilities...`,
  },
  {
    id: 40,
    title: "4K Smart TV",
    category: "Electronics",
    price: applyDiscount(699.99, 20),
    oldPrice: 699.99,
    discountPercent: 20,
    rating: 4.8,
    images: [
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 72 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Extra Large",
    color: "Black",
    variants: [
      {
        size: "55-inch",
        price: applyDiscount(699.99, 20),
        oldPrice: 699.99,
        stock: 8,
      },
      {
        size: "65-inch",
        price: applyDiscount(899.99, 20),
        oldPrice: 899.99,
        stock: 5,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Ryan Howard",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "The picture quality is stunning! Movies look incredible.",
      },
      {
        id: 2,
        author: "Andy Bernard",
        rating: 5,
        date: new Date(2023, 8, 28),
        comment: "Built-in streaming apps work flawlessly.",
      },
    ],
    details: `This 4K Ultra HD Smart TV features HDR technology for enhanced contrast and colors, a powerful processor for smooth performance, and built-in voice control...`,
  },
  {
    id: 41,
    title: "Garden Bench",
    category: "Garden",
    price: applyDiscount(199.99, 25),
    oldPrice: 199.99,
    discountPercent: 25,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Large",
    color: "Brown",
    variants: [
      {
        size: "3-seater",
        price: applyDiscount(199.99, 25),
        oldPrice: 199.99,
        stock: 7,
      },
      {
        size: "4-seater",
        price: applyDiscount(249.99, 25),
        oldPrice: 249.99,
        stock: 5,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Creed Bratton",
        rating: 4,
        date: new Date(2023, 5, 15),
        comment: "Sturdy construction that withstands the elements.",
      },
      {
        id: 2,
        author: "Phyllis Vance",
        rating: 5,
        date: new Date(2023, 4, 22),
        comment: "The perfect addition to my garden retreat.",
      },
    ],
    details: `This weather-resistant garden bench is crafted from durable materials with a classic design that complements any outdoor space...`,
  },
  {
    id: 42,
    title: "Patio Umbrella",
    category: "Garden",
    price: applyDiscount(149.99, 30),
    oldPrice: 149.99,
    discountPercent: 30,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Large",
    color: "Blue",
    variants: [
      {
        size: "7ft",
        price: applyDiscount(149.99, 30),
        oldPrice: 149.99,
        stock: 10,
      },
      {
        size: "9ft",
        price: applyDiscount(179.99, 30),
        oldPrice: 179.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Michael Scott",
        rating: 4,
        date: new Date(2023, 6, 10),
        comment: "Provides excellent shade for our patio table.",
      },
      {
        id: 2,
        author: "Jim Halpert",
        rating: 5,
        date: new Date(2023, 5, 5),
        comment: "The crank system makes it easy to open and close.",
      },
    ],
    details: `This patio umbrella features a durable canopy with UV protection, a easy-to-use crank system, and a sturdy base for stability in windy conditions...`,
  },
  {
    id: 43,
    title: "Plant Stand",
    category: "Garden",
    price: applyDiscount(79.99, 25),
    oldPrice: 79.99,
    discountPercent: 25,
    rating: 4.3,
    images: [
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "Brown",
    variants: [
      {
        size: "3-tier",
        price: applyDiscount(79.99, 25),
        oldPrice: 79.99,
        stock: 12,
      },
      {
        size: "5-tier",
        price: applyDiscount(119.99, 25),
        oldPrice: 119.99,
        stock: 8,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Pam Beesly",
        rating: 4,
        date: new Date(2023, 7, 18),
        comment: "Perfect for displaying my plant collection!",
      },
      {
        id: 2,
        author: "Angela Martin",
        rating: 5,
        date: new Date(2023, 6, 30),
        comment: "Sturdy construction that holds all my heavy pots.",
      },
    ],
    details: `This multi-tier plant stand provides elegant display space for your plants while saving floor space, with a durable weather-resistant finish...`,
  },
  {
    id: 44,
    title: "Outdoor String Lights",
    category: "Garden",
    price: applyDiscount(49.99, 40),
    oldPrice: 49.99,
    discountPercent: 40,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/cd/ef/12/cdef1234567890abcdef1234567890ab.jpg",
    ],
    countdownEnd: new Date(now + 18 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Medium",
    color: "White",
    variants: [
      {
        size: "25ft",
        price: applyDiscount(49.99, 40),
        oldPrice: 49.99,
        stock: 20,
      },
      {
        size: "50ft",
        price: applyDiscount(89.99, 40),
        oldPrice: 89.99,
        stock: 15,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Kelly Kapoor",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "Creates such a magical atmosphere in my backyard!",
      },
      {
        id: 2,
        author: "Erin Hannon",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "Weather-resistant and durable through all seasons.",
      },
    ],
    details: `These weather-resistant outdoor string lights feature warm white LED bulbs that create a cozy ambiance for evening gatherings...`,
  },
  {
    id: 45,
    title: "BBQ Grill",
    category: "Garden",
    price: applyDiscount(299.99, 20),
    oldPrice: 299.99,
    discountPercent: 20,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Casual",
    size: "Large",
    color: "Black",
    variants: [
      {
        size: "3-burner",
        price: applyDiscount(299.99, 20),
        oldPrice: 299.99,
        stock: 6,
      },
      {
        size: "4-burner",
        price: applyDiscount(399.99, 20),
        oldPrice: 399.99,
        stock: 4,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Kevin Malone",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "Perfect for my famous chili cookoffs!",
      },
      {
        id: 2,
        author: "Darryl Philbin",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "Even heat distribution and plenty of cooking space.",
      },
    ],
    details: `This propane BBQ grill features multiple burners for precise temperature control, a built-in thermometer, and side shelves for food preparation...`,
  },
  {
    id: 46,
    title: "Desk Organizer",
    category: "Office",
    price: applyDiscount(39.99, 35),
    oldPrice: 39.99,
    discountPercent: 35,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/ef/12/34/ef1234567890abcdef1234567890abcd.jpg",
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Small",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(39.99, 35),
        oldPrice: 39.99,
        stock: 25,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Oscar Martinez",
        rating: 5,
        date: new Date(2023, 5, 15),
        comment: "Finally, my desk is clutter-free and organized!",
      },
      {
        id: 2,
        author: "Angela Martin",
        rating: 4,
        date: new Date(2023, 4, 22),
        comment: "Sturdy construction with compartments for everything.",
      },
    ],
    details: `This desk organizer features multiple compartments for pens, paper clips, notepads, and other office supplies, helping you maintain a tidy workspace...`,
  },
  {
    id: 47,
    title: "Ergonomic Office Chair",
    category: "Office",
    price: applyDiscount(249.99, 20),
    oldPrice: 249.99,
    discountPercent: 20,
    rating: 4.6,
    images: [
      "https://i.pinimg.com/736x/12/34/56/1234567890abcdef1234567890abcdef.jpg",
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
    ],
    countdownEnd: new Date(now + 36 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(249.99, 20),
        oldPrice: 249.99,
        stock: 10,
      },
      {
        size: "Executive",
        price: applyDiscount(299.99, 20),
        oldPrice: 299.99,
        stock: 7,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Toby Flenderson",
        rating: 5,
        date: new Date(2023, 6, 10),
        comment:
          "My back pain has significantly reduced since using this chair.",
      },
      {
        id: 2,
        author: "Holly Flax",
        rating: 4,
        date: new Date(2023, 5, 5),
        comment: "Adjustable features make it perfect for long work days.",
      },
    ],
    details: `This ergonomic office chair features lumbar support, adjustable height and armrests, breathable mesh back, and comfortable cushioning for all-day comfort...`,
  },
  {
    id: 48,
    title: "Desk Lamp",
    category: "Office",
    price: applyDiscount(59.99, 30),
    oldPrice: 59.99,
    discountPercent: 30,
    rating: 4.5,
    images: [
      "https://i.pinimg.com/736x/34/56/78/34567890abcdef1234567890abcdef12.jpg",
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
    ],
    countdownEnd: new Date(now + 24 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Silver",
    variants: [
      {
        size: "Standard",
        price: applyDiscount(59.99, 30),
        oldPrice: 59.99,
        stock: 18,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Pam Beesly",
        rating: 4,
        date: new Date(2023, 7, 18),
        comment: "Adjustable brightness is perfect for different tasks.",
      },
      {
        id: 2,
        author: "Jim Halpert",
        rating: 5,
        date: new Date(2023, 6, 30),
        comment: "Sleek design that doesn't take up much desk space.",
      },
    ],
    details: `This LED desk lamp features adjustable brightness levels, color temperatures, and a flexible gooseneck design for precise lighting control...`,
  },
  {
    id: 49,
    title: "File Cabinet",
    category: "Office",
    price: applyDiscount(129.99, 25),
    oldPrice: 129.99,
    discountPercent: 25,
    rating: 4.4,
    images: [
      "https://i.pinimg.com/736x/56/78/90/567890abcdef1234567890abcdef1234.jpg",
      "https://i.pinimg.com/736x/90/ab/cd/90abcd1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 48 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Medium",
    color: "Black",
    variants: [
      {
        size: "2-drawer",
        price: applyDiscount(129.99, 25),
        oldPrice: 129.99,
        stock: 9,
      },
      {
        size: "4-drawer",
        price: applyDiscount(189.99, 25),
        oldPrice: 189.99,
        stock: 6,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Oscar Martinez",
        rating: 5,
        date: new Date(2023, 8, 5),
        comment: "Secure locking mechanism for important documents.",
      },
      {
        id: 2,
        author: "Angela Martin",
        rating: 4,
        date: new Date(2023, 7, 22),
        comment: "Smooth-gliding drawers with plenty of storage space.",
      },
    ],
    details: `This sturdy file cabinet features smooth-gliding drawers, a secure locking mechanism, and a durable finish that resists scratches and dents...`,
  },
  {
    id: 50,
    title: "Standing Desk",
    category: "Office",
    price: applyDiscount(399.99, 20),
    oldPrice: 399.99,
    discountPercent: 20,
    rating: 4.7,
    images: [
      "https://i.pinimg.com/736x/78/90/ab/7890abcdef1234567890abcdef123456.jpg",
      "https://i.pinimg.com/736x/ab/cd/ef/abcdef1234567890abcdef1234567890.jpg",
    ],
    countdownEnd: new Date(now + 72 * 60 * 60 * 1000),
    status: "In Stock",
    style: "Formal",
    size: "Large",
    color: "Brown",
    variants: [
      {
        size: "48-inch",
        price: applyDiscount(399.99, 20),
        oldPrice: 399.99,
        stock: 7,
      },
      {
        size: "60-inch",
        price: applyDiscount(499.99, 20),
        oldPrice: 499.99,
        stock: 5,
      },
    ],
    reviews: [
      {
        id: 1,
        author: "Dwight Schrute",
        rating: 5,
        date: new Date(2023, 9, 12),
        comment: "Electric height adjustment is smooth and quiet.",
      },
      {
        id: 2,
        author: "Michael Scott",
        rating: 4,
        date: new Date(2023, 8, 28),
        comment: "My productivity has increased since switching to standing.",
      },
    ],
    details: `This electric standing desk features quiet height adjustment, programmable memory settings, and a spacious desktop that accommodates multiple monitors...`,
  },
];
